#!/bin/sh

pass=true
RED='\033[1;31m'
GREEN='\033[0;32m'
NC='\033[0m'

cd Cooper

# Backend tests
echo "Running backend tests:"
backendTest=$(dotnet test)
ret_code=$?

if [ $ret_code != 0 ]; then
	printf "\n${RED}Backend tests failed:${NC}"
	echo "$backendTest\n"
	pass=false
else
	printf "${GREEN}Backend tests passed.${NC}\n"
fi

# Build backend project
echo "Building backend project:"
backendBuild=$(dotnet build)
ret_code=$?

if [ $ret_code != 0 ]; then
	printf "\n${RED}Backend build failed:${NC}"
	echo "$backendBuild\n"
	pass=false
else
	printf "${GREEN}Backend build passed.${NC}\n"
fi


cd ClientApp

# Linter
echo "Running Linters:"
tslint=$(npm run lint)
ret_code=$?

if [ $ret_code != 0 ]; then
	printf "\n${RED}Tslint failed:${NC}"
	echo "$tslint\n"
	pass=false
else
	printf "${GREEN}Tslint passed.${NC}\n"
fi

# Build frontend project
echo "Building frontend project:"
frontendBuild=$(npm run build)
ret_code=$?

if [ $ret_code != 0 ]; then
	printf "${RED}Frontend build failed:${NC}"
	echo "$frontendBuild\n"
	pass=false
else
	printf "${GREEN}Frontend build passed.${NC}\n"
fi

if $pass; then
	exit 0
fi

exit 1