//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDBUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OracleDBUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;DB_VERSION_TABLE&quot;: &quot;DB_VERSION&quot;,
        ///  &quot;DB_VERSION_FIELD&quot;: &quot;VERSION&quot;,
        ///  &quot;ConnectionString&quot;: &quot;User Id=SYSTEM;Password=qQ1111qQ;Data Source=localhost:1521/xe;&quot;,
        ///  &quot;GITHUB_PATH&quot;: &quot;vanmxpx/ISDPlatform/contents/Documentation/Database/UpdateScripts&quot;
        ///}.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;update&quot;: &quot;UPDATE IS \nTHE BEST \nCOMMAND\n&quot;,
        ///  &quot;import&quot;: &quot;import [TABLE_NAME]&quot;,
        ///  &quot;export&quot;: &quot;export [TABLE_NAME] [SkipField1,SkipField2]&quot;,
        ///  &quot;github&quot;: &quot;\&quot;github update\&quot; command can allow you to download last update scripts from GitHub repository.\n&quot;,
        ///  &quot;version&quot;: &quot;The \&quot;version\&quot; command displays the current version of the database. This command has no additional parameters.&quot;,
        ///  &quot;versions&quot;: &quot;The \&quot;versions\&quot; command displays all versions of the database. This command has no additional parameters [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual {
            get {
                return ResourceManager.GetString("manual", resourceCulture);
            }
        }
    }
}
